Various small improvements / fixes
CrashOveride95/ultrasm64 pull request #38
Opened 2023-03-11 22:44 UTC by gheskett

- [Frustum Fix: Revert frustum ratio back to 2](https://github.com/CrashOveride95/ultrasm64/commit/eda46e5d6484dea72484a43305da3161b44f2d94)
- [Fix builds on Make 4.4 (#588)](https://github.com/CrashOveride95/ultrasm64/commit/4e45ade43bb500057edd1a76c19704fd1dc33cac)
- [remove warnings from rnc1/2 files (#468)](https://github.com/CrashOveride95/ultrasm64/commit/931b9af31f8826b9cb55520d603a4e2dcd83e34d)

2023-03-11 22:58 UTC, CrashOveride95 commented
Did you test it this time?

2023-03-11 23:47 UTC, gheskett commented
I'm assuming it's been tested thoroughly at this point, here's some context:
![image](https://user-images.githubusercontent.com/22061597/224516585-f61ca9a3-856f-4113-890d-7fbecd842fed.png)

If we do end up discovering any additional issues later on for some reason (which I probably would at least), we can PR additional fixes.

2023-09-04 23:17 UTC, Reonu commented
true!

2023-09-05 00:26 UTC, mountainflaw requested changes
Hi. I originally implemented and tested the microcode changes originally. My only comment is to remove the `gSPClipRatio` entry in `init_rsp`. F3DEX2/ZEX initializes this to `FRUSTRATIO_2` by default already, and `init_rsp` is only called once per game boot.

2023-09-05 03:57 UTC, gheskett commented
Is there any real practical upside to removing it? Taking it out becomes a 'knowledge issue', since it's more obvious what the clip ratio is set to if it's set explicitly.

2023-09-07 20:30 UTC, gheskett commented
Reverted frustratio changes, as more rendering issues have been discovered; it's not worth dealing with a change that finnicky. The other two changes should be safe to merge though.

2023-09-07 20:53 UTC, merged